M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu22.04.1} date 2024-09-17T12:21:12-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-17T12:21:12-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0335
%
G90
G05
T1
X3.4961Y-2.2013
X3.6142Y-2.2013
M30
